#!/bin/bash

set -e

echo $$

which afp &> /dev/null || echo "Executable 'afp' no found in your $PATH"
which timeout &> /dev/null || echo "Executable 'timeout' not found in your $PATH. Maybe you need to install package 'coreutils'...?"

TIMEOUT=3559

while true
do
	timeout --foreground ${TIMEOUT} afp $*
done
